name: 'CI/CD for AWS EC2'

on:
  push:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

        env:
          CI: true
  
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
              . ~/.nvm/nvm.sh

              nvm install 18
              npm install -g pm2
              cd ~/node-cicd
              git pull origin main
              touch .env
              echo ${{secrets.ENV_FILE}} >> .env
              npm install
              npm run build
              pm2 start npm --name node-cicd-api -- run start:prod

          
